name: flutter_wave
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.0.0+3

  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  path: ^1.9.0
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  get: ^4.6.5
  

dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo_wave.png
